### ISSUE TITLE
Fix issue when replacing worse-quality files

### ISSUE THREAD

**Issue by gfitzp** [gfitzp/fitzflix#104]
Traceback (most recent call last):
 File "/Users/server/Sites/fitzflix/app/videos.py", line 995, in finalize_localization
   worse.quality.physical_media == file.quality.physical_media
   ^^^^^^^^^^^^^
 File "/Users/server/Sites/fitzflix/venv/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 480, in __get__
   return self.impl.get(state, dict_)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Users/server/Sites/fitzflix/venv/lib/python3.11/site-packages/sqlalchemy/orm/attributes.py", line 931, in get
   value = self.callable_(state, passive)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Users/server/Sites/fitzflix/venv/lib/python3.11/site-packages/sqlalchemy/orm/strategies.py", line 832, in _load_for_state
   raise orm_exc.DetachedInstanceError(
sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <File at 0x104e26010> is not bound to a Session; lazy load operation of attribute 'quality' cannot proceed (Background on this error at: http://sqlalche.me/e/14/bhk3)

**Comment by gfitzp** [comment]
Fixed in 4417472
