### ISSUE TITLE
Subtitle track index out of range

### ISSUE THREAD

**Issue by gfitzp** [gfitzp/fitzflix#105]
```
Traceback (most recent call last):
 File "/Users/server/Sites/fitzflix/app/videos.py", line 322, in localization_task
   subtitle_tracks = get_subtitle_tracks_from_file(file_path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Users/server/Sites/fitzflix/app/videos.py", line 3364, in get_subtitle_tracks_from_file
   subtitle_track["language"] = language[3]
                                ~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by gfitzp** [comment]
Fixed in 361572c8fb5074a2fc81d882292c67670b1069bf
