### ISSUE TITLE
Fix password reset

### ISSUE THREAD

**Issue by gfitzp** [gfitzp/fitzflix#18]
```
Exception on /auth/reset-password-request [POST]
Traceback (most recent call last):
  File "/Users/gfitzp/Sites/fitzflix/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gfitzp/Sites/fitzflix/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gfitzp/Sites/fitzflix/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gfitzp/Sites/fitzflix/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/gfitzp/Sites/fitzflix/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gfitzp/Sites/fitzflix/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/gfitzp/Sites/fitzflix/app/auth/routes.py", line 78, in reset_password_request
    send_password_reset_email(user)
  File "/Users/gfitzp/Sites/fitzflix/app/auth/email.py", line 9, in send_password_reset_email
    sender=app.config["ADMIN_EMAIL"],
NameError: name 'app' is not defined
```

**Comment by gfitzp** [comment]
Fixed in d19187d7eb6bea4b2fda3efa26de1ac65f756005
