### ISSUE TITLE
Increase S3 upload retries

### ISSUE THREAD

**Issue by gfitzp** [gfitzp/fitzflix#2]
```
Traceback (most recent call last):
  File "./app/videos.py", line 178, in localization_task
    ) = aws_upload(file_path, current_app.config["AWS_UNTOUCHED_PREFIX"])
  File "./app/videos.py", line 1358, in aws_upload
    response = s3_client.upload_file(
  File "/Users/server/Sites/fitzflix/venv/lib/python3.8/site-packages/boto3/s3/inject.py", line 129, in upload_file
    return transfer.upload_file(
  File "/Users/server/Sites/fitzflix/venv/lib/python3.8/site-packages/boto3/s3/transfer.py", line 285, in upload_file
    raise S3UploadFailedError(
boto3.exceptions.S3UploadFailedError: Failed to upload /Volumes/Media/videos/renamed/Sleepwalking Land (2007) - [HDTV-720p].mkv to aws-us-east-1-medialibrary.glennfitzpatrick.com/untouched/Sleepwalking Land (2007) - [HDTV-720p].mkv: An error occurred (InternalError) when calling the UploadPart operation (reached max retries: 0): We encountered an internal error. Please try again.
```

**Comment by gfitzp** [comment]
Updated to 3 retries in 3829caf
