### ISSUE TITLE
Only show jobs that exist in on the Queue page

### ISSUE THREAD

**Issue by gfitzp** [gfitzp/fitzflix#39]
```
Exception on /queue [GET]
Traceback (most recent call last):
  File "/Users/server/Sites/fitzflix/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/server/Sites/fitzflix/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/server/Sites/fitzflix/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/server/Sites/fitzflix/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/server/Sites/fitzflix/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/server/Sites/fitzflix/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/server/Sites/fitzflix/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/server/Sites/fitzflix/app/main/routes.py", line 1670, in queue
    job = Job.fetch(job_id, connection=current_app.redis)
  File "/Users/server/Sites/fitzflix/venv/lib/python3.8/site-packages/rq/job.py", line 299, in fetch
    job.refresh()
  File "/Users/server/Sites/fitzflix/venv/lib/python3.8/site-packages/rq/job.py", line 518, in refresh
    raise NoSuchJobError('No such job: {0}'.format(self.key))
rq.exceptions.NoSuchJobError: No such job: b'rq:job:The Owl and the Raven- An Eskimo Legend (1973) - [WEBDL-1080p].mkv'
```

**Comment by gfitzp** [comment]
Fixed in 3000b296437bb1f2cd9bc0c10b625d62ab62d0aa
