### ISSUE TITLE
Bug with Sonarr password verification code?

### ISSUE THREAD

**Issue by gfitzp** [gfitzp/fitzflix#77]
```
Exception on /api/sonarr/add [POST]
Traceback (most recent call last):
  File "/Users/gfitzp/Sites/fitzflix/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gfitzp/Sites/fitzflix/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gfitzp/Sites/fitzflix/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gfitzp/Sites/fitzflix/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/gfitzp/Sites/fitzflix/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gfitzp/Sites/fitzflix/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/gfitzp/Sites/fitzflix/app/api/sonarr.py", line 31, in add
    if user is None or not user.check_password(
  File "/Users/gfitzp/Sites/fitzflix/app/models.py", line 850, in check_password
    return check_password_hash(self.password_hash, password)
  File "/Users/gfitzp/Sites/fitzflix/venv/lib/python3.9/site-packages/werkzeug/security.py", line 221, in check_password_hash
    return safe_str_cmp(_hash_internal(method, salt, password)[0], hashval)
  File "/Users/gfitzp/Sites/fitzflix/venv/lib/python3.9/site-packages/werkzeug/security.py", line 153, in _hash_internal
    rv = pbkdf2_hex(password, salt, iterations, hashfunc=method)
  File "/Users/gfitzp/Sites/fitzflix/venv/lib/python3.9/site-packages/werkzeug/security.py", line 54, in pbkdf2_hex
    return to_native(codecs.encode(rv, "hex_codec"))
LookupError: unknown encoding: hex_codec
```

**Comment by gfitzp** [comment]
Haven't seen the bug appear in a while, closing issue.
