### ISSUE TITLE
Unable to save reviews

### ISSUE THREAD

**Issue by gfitzp** [gfitzp/fitzflix#83]
Exception on /movie/1408 [POST]
Traceback (most recent call last):
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
   self.dialect.do_execute(
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
   cursor.execute(statement, parameters)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/pymysql/cursors.py", line 148, in execute
   result = self._query(query)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/pymysql/cursors.py", line 310, in _query
   conn.query(q)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/pymysql/connections.py", line 548, in query
   self._affected_rows = self._read_query_result(unbuffered=unbuffered)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/pymysql/connections.py", line 775, in _read_query_result
   result.read()
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/pymysql/connections.py", line 1156, in read
   first_packet = self.connection._read_packet()
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
   packet.raise_for_error()
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
   err.raise_mysql_exception(self._data)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
   raise errorclass(errno, errval)
pymysql.err.OperationalError: (1292, "Incorrect datetime value: '<built-in method utcnow of type object at 0x10d16b978>' for column `fitzflix_db`.`user_movie_review`.`date_reviewed` at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
   response = self.full_dispatch_request()
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
   rv = self.handle_user_exception(e)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
   rv = self.dispatch_request()
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
   return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
   return func(*args, **kwargs)
 File "/Users/server/Sites/fitzflix/app/main/routes.py", line 488, in movie
   db.session.commit()
 File "<string>", line 2, in commit
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1428, in commit
   self._transaction.commit(_to_root=self.future)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 829, in commit
   self._prepare_impl()
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
   self.session.flush()
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3286, in flush
   self._flush(objects)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3426, in _flush
   transaction.rollback(_capture_exception=True)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
   compat.raise_(
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
   raise exception
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3386, in _flush
   flush_context.execute()
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
   rec.execute(self)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
   util.preloaded.orm_persistence.save_obj(
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 242, in save_obj
   _emit_insert_statements(
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1219, in _emit_insert_statements
   result = connection._execute_20(
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
   return meth(self, args_10style, kwargs_10style, execution_options)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 324, in _execute_on_connection
   return connection._execute_clauseelement(
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1451, in _execute_clauseelement
   ret = self._execute_context(
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
   self._handle_dbapi_exception(
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1994, in _handle_dbapi_exception
   util.raise_(
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
   raise exception
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
   self.dialect.do_execute(
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
   cursor.execute(statement, parameters)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/pymysql/cursors.py", line 148, in execute
   result = self._query(query)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/pymysql/cursors.py", line 310, in _query
   conn.query(q)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/pymysql/connections.py", line 548, in query
   self._affected_rows = self._read_query_result(unbuffered=unbuffered)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/pymysql/connections.py", line 775, in _read_query_result
   result.read()
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/pymysql/connections.py", line 1156, in read
   first_packet = self.connection._read_packet()
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
   packet.raise_for_error()
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
   err.raise_mysql_exception(self._data)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
   raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1292, "Incorrect datetime value: '<built-in method utcnow of type object at 0x10d16b978>' for column `fitzflix_db`.`user_movie_review`.`date_reviewed` at row 1")
[SQL: INSERT INTO user_movie_review (user_id, movie_id, rating, modified_rating, whole_stars, half_stars, review, date_watched, date_reviewed) VALUES (%(user_id)s, %(movie_id)s, %(rating)s, %(modified_rating)s, %(whole_stars)s, %(half_stars)s, %(review)s, %(date_watched)s, %(date_reviewed)s)]
[parameters: {'user_id': 1, 'movie_id': 1408, 'rating': Decimal('4'), 'modified_rating': 4.0, 'whole_stars': 4, 'half_stars': 0, 'review': '', 'date_watched': datetime.date(2021, 6, 7), 'date_reviewed': <built-in method utcnow of type object at 0x10d16b978>}]
(Background on this error at: http://sqlalche.me/e/14/e3q8)

**Comment by gfitzp** [comment]
Fixed in 9e52a0b7314a494a76484b190b8ac8e246a649e4
