### ISSUE TITLE
Check first to see if a TMDB entry already exists before trying to add

### ISSUE THREAD

**Issue by gfitzp** [gfitzp/fitzflix#93]
```
Traceback (most recent call last):
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
   self.dialect.do_execute(
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
   cursor.execute(statement, parameters)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
   result = self._query(query)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
   conn.query(q)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
   self._affected_rows = self._read_query_result(unbuffered=unbuffered)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
   result.read()
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
   first_packet = self.connection._read_packet()
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
   packet.raise_for_error()
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
   err.raise_mysql_exception(self._data)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
   raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry 'Léon: The Professional-1994' for key 'title'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
 File "/Users/server/Sites/fitzflix/app/videos.py", line 3005, in refresh_tmdb_info
   updated_tmdb_id = movie.tmdb_id
 File "/Users/server/Sites/fitzflix/app/models.py", line 308, in tmdb_movie_query
   ).first()
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2750, in first
   return self.limit(1)._iter().first()
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2834, in _iter
   result = self.session.execute(
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1634, in execute
   ) = compile_state_cls.orm_pre_session_exec(
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 283, in orm_pre_session_exec
   session._autoflush()
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2192, in _autoflush
   util.raise_(e, with_traceback=sys.exc_info()[2])
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
   raise exception
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2181, in _autoflush
   self.flush()
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3286, in flush
   self._flush(objects)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3425, in _flush
   with util.safe_reraise():
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
   compat.raise_(
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
   raise exception
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3386, in _flush
   flush_context.execute()
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
   rec.execute(self)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
   util.preloaded.orm_persistence.save_obj(
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 234, in save_obj
   _emit_update_statements(
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 998, in _emit_update_statements
   c = connection._execute_20(
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
   return meth(self, args_10style, kwargs_10style, execution_options)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 324, in _execute_on_connection
   return connection._execute_clauseelement(
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1451, in _execute_clauseelement
   ret = self._execute_context(
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
   self._handle_dbapi_exception(
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1994, in _handle_dbapi_exception
   util.raise_(
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
   raise exception
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
   self.dialect.do_execute(
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
   cursor.execute(statement, parameters)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
   result = self._query(query)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
   conn.query(q)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
   self._affected_rows = self._read_query_result(unbuffered=unbuffered)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
   result.read()
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
   first_packet = self.connection._read_packet()
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
   packet.raise_for_error()
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
   err.raise_mysql_exception(self._data)
 File "/Users/server/Sites/fitzflix/venv/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
   raise errorclass(errno, errval)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(pymysql.err.IntegrityError) (1062, "Duplicate entry 'Léon: The Professional-1994' for key 'title'")
[SQL: UPDATE movie SET title=%(title)s, imdb_id=%(imdb_id)s, tmdb_id=%(tmdb_id)s, tmdb_adult=%(tmdb_adult)s, tmdb_backdrop_path=%(tmdb_backdrop_path)s, tmdb_budget=%(tmdb_budget)s, tmdb_homepage=%(tmdb_homepage)s, tmdb_original_language=%(tmdb_original_language)s, tmdb_original_title=%(tmdb_original_title)s, tmdb_overview=%(tmdb_overview)s, tmdb_popularity=%(tmdb_popularity)s, tmdb_poster_path=%(tmdb_poster_path)s, tmdb_release_date=%(tmdb_release_date)s, tmdb_revenue=%(tmdb_revenue)s, tmdb_runtime=%(tmdb_runtime)s, tmdb_status=%(tmdb_status)s, tmdb_tagline=%(tmdb_tagline)s, tmdb_title=%(tmdb_title)s, tmdb_video=%(tmdb_video)s, tmdb_vote_average=%(tmdb_vote_average)s, tmdb_vote_count=%(tmdb_vote_count)s, tmdb_data_as_of=%(tmdb_data_as_of)s WHERE [movie.id](http://movie.id/) = %(movie_id)s]
[parameters: {'title': 'Léon: The Professional', 'imdb_id': 'tt0110413', 'tmdb_id': 101, 'tmdb_adult': 0, 'tmdb_backdrop_path': '/jRJrQ72VLyEnVsvwfep8Xjlvu8c.jpg', 'tmdb_budget': 16000000, 'tmdb_homepage': '', 'tmdb_original_language': 'en', 'tmdb_original_title': 'Léon: The Professional', 'tmdb_overview': 'Léon, the top hit man in New York, has earned a rep as an effective "cleaner". But when his next-door neighbors are wiped out by a loose-cannon DEA a ... (17 characters truncated) ... the unwilling custodian of 12-year-old Mathilda. Before long, Mathilda\'s thoughts turn to revenge, and she considers following in Léon\'s footsteps.', 'tmdb_popularity': 55.907, 'tmdb_poster_path': '/yI6X2cCM5YPJtxMhUd3dPGqDAhw.jpg', 'tmdb_release_date': datetime.datetime(1994, 9, 14, 0, 0), 'tmdb_revenue': 45284974, 'tmdb_runtime': 111, 'tmdb_status': 'Released', 'tmdb_tagline': 'If you want a job done well, hire a professional.', 'tmdb_title': 'Léon: The Professional', 'tmdb_video': 0, 'tmdb_vote_average': 8.322, 'tmdb_vote_count': 12756, 'tmdb_data_as_of': datetime.datetime(2022, 12, 29, 14, 58, 20, 212124), 'movie_id': 3202}]
(Background on this error at: http://sqlalche.me/e/14/gkpj)
```

**Comment by gfitzp** [comment]
Fixed in 441854f4d6d3c7e0309a57d9edbc79063a4db678
